apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-3e00
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-3e00@sha256:b2aaa68e0ff97b93c63293e85add3292b388225e88388ea7e6e0471c4b5fd992
        name: my-python
        resources: {}
status: {}
