apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-lurc
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-lurc@sha256:645afbed46356c4675be5fc25be01481a5eb858bfecd9b0e1b2396039a85af93
        name: my-nodejs
        resources: {}
status: {}
